import { integer, primaryKey, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const timestamps = { createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()) };

export const adminUsers = sqliteTable('admin_users', { id: text('id').primaryKey(), email: text('email').notNull().unique(), passwordHash: text('password_hash').notNull(), name: text('name').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const productCategories = sqliteTable('product_categories', { id: text('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), sortOrder: integer('sort_order').notNull().default(0), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const products = sqliteTable('products', { id: text('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), internalName: text('internal_name').notNull(), shortDescription: text('short_description'), description: text('description').notNull(), price: integer('price').notNull(), compareAtPrice: integer('compare_at_price'), currency: text('currency').notNull().default('BRL'), active: integer('active', { mode: 'boolean' }).notNull().default(true), featured: integer('featured', { mode: 'boolean' }).notNull().default(false), coverImage: text('cover_image'), mobileImage: text('mobile_image'), deliveryType: text('delivery_type').notNull().default('digital'), digitalFile: text('digital_file'), categoryId: text('category_id').references(() => productCategories.id), seoTitle: text('seo_title'), seoDescription: text('seo_description'), sortOrder: integer('sort_order').notNull().default(0), ...timestamps });
export const productImages = sqliteTable('product_images', { id: text('id').primaryKey(), productId: text('product_id').notNull().references(() => products.id, { onDelete: 'cascade' }), url: text('url').notNull(), alt: text('alt').notNull(), sortOrder: integer('sort_order').notNull().default(0), ...timestamps });
export const bundles = sqliteTable('bundles', { id: text('id').primaryKey(), name: text('name').notNull(), internalName: text('internal_name').notNull(), slug: text('slug').notNull().unique(), shortDescription: text('short_description'), description: text('description').notNull(), image: text('image'), mobileImage: text('mobile_image'), price: integer('price').notNull(), compareAtPrice: integer('compare_at_price'), currency: text('currency').notNull().default('BRL'), badgeText: text('badge_text'), ctaText: text('cta_text').notNull(), recommended: integer('recommended', { mode: 'boolean' }).notNull().default(false), defaultSelected: integer('default_selected', { mode: 'boolean' }).notNull().default(false), active: integer('active', { mode: 'boolean' }).notNull().default(true), sortOrder: integer('sort_order').notNull().default(0), startDate: integer('start_date', { mode: 'timestamp' }), endDate: integer('end_date', { mode: 'timestamp' }), ...timestamps });
export const bundleItems = sqliteTable('bundle_items', { bundleId: text('bundle_id').notNull().references(() => bundles.id, { onDelete: 'cascade' }), productId: text('product_id').notNull().references(() => products.id), quantity: integer('quantity').notNull().default(1), sortOrder: integer('sort_order').notNull().default(0) }, (table) => [primaryKey({ columns: [table.bundleId, table.productId] })]);
export const orderBumps = sqliteTable('order_bumps', { id: text('id').primaryKey(), name: text('name').notNull(), internalName: text('internal_name').notNull(), headline: text('headline').notNull(), description: text('description').notNull(), productId: text('product_id').notNull().references(() => products.id), priceOverride: integer('price_override'), image: text('image'), badgeText: text('badge_text'), ctaText: text('cta_text').notNull(), location: text('location').notNull().default('cart'), conditions: text('conditions', { mode: 'json' }), active: integer('active', { mode: 'boolean' }).notNull().default(true), priority: integer('priority').notNull().default(0), startDate: integer('start_date', { mode: 'timestamp' }), endDate: integer('end_date', { mode: 'timestamp' }), ...timestamps });
export const cartOffers = sqliteTable('cart_offers', { id: text('id').primaryKey(), name: text('name').notNull(), internalName: text('internal_name').notNull(), headline: text('headline').notNull(), description: text('description').notNull(), productId: text('product_id').notNull().references(() => products.id), image: text('image'), priceOverride: integer('price_override'), ctaText: text('cta_text').notNull(), conditions: text('conditions', { mode: 'json' }), active: integer('active', { mode: 'boolean' }).notNull().default(true), priority: integer('priority').notNull().default(0), ...timestamps });
export const bonuses = sqliteTable('bonuses', { id: text('id').primaryKey(), name: text('name').notNull(), description: text('description').notNull(), productId: text('product_id').references(() => products.id), value: integer('value'), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const exitOffers = sqliteTable('exit_offers', { id: text('id').primaryKey(), stage: integer('stage').notNull().unique(), name: text('name').notNull(), internalName: text('internal_name').notNull(), headline: text('headline').notNull(), subheadline: text('subheadline'), description: text('description').notNull(), image: text('image'), offerType: text('offer_type').notNull(), productId: text('product_id').references(() => products.id), bundleId: text('bundle_id').references(() => bundles.id), discountType: text('discount_type'), discountValue: integer('discount_value'), bonusId: text('bonus_id').references(() => bonuses.id), ctaText: text('cta_text').notNull(), secondaryText: text('secondary_text'), active: integer('active', { mode: 'boolean' }).notNull().default(true), startDate: integer('start_date', { mode: 'timestamp' }), endDate: integer('end_date', { mode: 'timestamp' }), ...timestamps });
export const orders = sqliteTable('orders', { id: text('id').primaryKey(), orderNumber: text('order_number').notNull().unique(), customerName: text('customer_name'), customerEmail: text('customer_email'), status: text('status').notNull().default('pending'), paymentStatus: text('payment_status').notNull().default('pending'), subtotal: integer('subtotal').notNull(), discount: integer('discount').notNull().default(0), total: integer('total').notNull(), currency: text('currency').notNull().default('BRL'), stripePaymentIntentId: text('stripe_payment_intent_id').unique(), stripeCheckoutSessionId: text('stripe_checkout_session_id').unique(), stripeCustomerId: text('stripe_customer_id'), downloadToken: text('download_token').unique(), ...timestamps });
export const orderItems = sqliteTable('order_items', { id: text('id').primaryKey(), orderId: text('order_id').notNull().references(() => orders.id, { onDelete: 'cascade' }), productId: text('product_id').references(() => products.id), bundleId: text('bundle_id').references(() => bundles.id), titleSnapshot: text('title_snapshot').notNull(), quantity: integer('quantity').notNull().default(1), unitPrice: integer('unit_price').notNull(), total: integer('total').notNull(), itemType: text('item_type').notNull(), ...timestamps });
export const digitalAssets = sqliteTable('digital_assets', { id: text('id').primaryKey(), productId: text('product_id').notNull().references(() => products.id), fileKey: text('file_key').notNull(), fileName: text('file_name').notNull(), contentType: text('content_type').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const testimonials = sqliteTable('testimonials', { id: text('id').primaryKey(), name: text('name').notNull(), text: text('text').notNull(), photo: text('photo'), rating: integer('rating').notNull(), city: text('city'), verified: integer('verified', { mode: 'boolean' }).notNull().default(false), active: integer('active', { mode: 'boolean' }).notNull().default(false), sortOrder: integer('sort_order').notNull().default(0), ...timestamps });
export const faqs = sqliteTable('faqs', { id: text('id').primaryKey(), question: text('question').notNull(), answer: text('answer').notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), sortOrder: integer('sort_order').notNull().default(0), ...timestamps });
export const salesPageConfigs = sqliteTable('sales_page_configs', { id: text('id').primaryKey(), internalName: text('internal_name').notNull(), content: text('content', { mode: 'json' }).notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const urgencyCampaigns = sqliteTable('urgency_campaigns', { id: text('id').primaryKey(), name: text('name').notNull(), message: text('message').notNull(), startDate: integer('start_date', { mode: 'timestamp' }), endDate: integer('end_date', { mode: 'timestamp' }), active: integer('active', { mode: 'boolean' }).notNull().default(false), ...timestamps });
export const promotions = sqliteTable('promotions', { id: text('id').primaryKey(), name: text('name').notNull(), code: text('code').unique(), discountType: text('discount_type').notNull(), discountValue: integer('discount_value').notNull(), conditions: text('conditions', { mode: 'json' }), active: integer('active', { mode: 'boolean' }).notNull().default(true), startDate: integer('start_date', { mode: 'timestamp' }), endDate: integer('end_date', { mode: 'timestamp' }), ...timestamps });
export const seoConfigs = sqliteTable('seo_configs', { id: text('id').primaryKey(), route: text('route').notNull().unique(), title: text('title').notNull(), description: text('description').notNull(), canonical: text('canonical'), openGraphImage: text('open_graph_image'), structuredData: text('structured_data', { mode: 'json' }), ...timestamps });
export const keywords = sqliteTable('keywords', { id: text('id').primaryKey(), keyword: text('keyword').notNull().unique(), category: text('category').notNull(), priority: integer('priority').notNull().default(0), intent: text('intent').notNull(), pages: text('pages', { mode: 'json' }), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const analyticsEvents = sqliteTable('analytics_events', { id: text('id').primaryKey(), name: text('name').notNull(), sessionId: text('session_id'), orderId: text('order_id'), payload: text('payload', { mode: 'json' }), createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()) });
export const siteSettings = sqliteTable('site_settings', { key: text('key').primaryKey(), value: text('value', { mode: 'json' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()) });
export const pixelIntegrations = sqliteTable('pixel_integrations', { id: text('id').primaryKey(), provider: text('provider').notNull().unique(), publicId: text('public_id'), active: integer('active', { mode: 'boolean' }).notNull().default(false), ...timestamps });
export const processedWebhooks = sqliteTable('processed_webhooks', { id: text('id').primaryKey(), type: text('type').notNull(), processedAt: integer('processed_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()) });
