create extension if not exists pgcrypto;

create table if not exists public.admin_users (id text primary key, email text not null unique, password_hash text not null, name text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.product_categories (id text primary key, name text not null, slug text not null unique, sort_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.products (id text primary key, name text not null, slug text not null unique, internal_name text not null, short_description text, description text not null, price integer not null, compare_at_price integer, currency text not null default 'BRL', active boolean not null default true, featured boolean not null default false, cover_image text, mobile_image text, delivery_type text not null default 'digital', digital_file text, category_id text references public.product_categories(id), seo_title text, seo_description text, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.product_images (id text primary key, product_id text not null references public.products(id) on delete cascade, url text not null, alt text not null, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bundles (id text primary key, name text not null, internal_name text not null, slug text not null unique, short_description text, description text not null, image text, mobile_image text, price integer not null, compare_at_price integer, currency text not null default 'BRL', badge_text text, cta_text text not null, recommended boolean not null default false, default_selected boolean not null default false, active boolean not null default true, sort_order integer not null default 0, start_date timestamptz, end_date timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bundle_items (bundle_id text not null references public.bundles(id) on delete cascade, product_id text not null references public.products(id), quantity integer not null default 1, sort_order integer not null default 0, primary key(bundle_id, product_id));
create table if not exists public.order_bumps (id text primary key, name text not null, internal_name text not null, headline text not null, description text not null, product_id text not null references public.products(id), price_override integer, image text, badge_text text, cta_text text not null, location text not null default 'cart', conditions jsonb, active boolean not null default true, priority integer not null default 0, start_date timestamptz, end_date timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.cart_offers (id text primary key, name text not null, internal_name text not null, headline text not null, description text not null, product_id text not null references public.products(id), image text, price_override integer, cta_text text not null, conditions jsonb, active boolean not null default true, priority integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.bonuses (id text primary key, name text not null, description text not null, product_id text references public.products(id), value integer, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.exit_offers (id text primary key, stage integer not null unique, name text not null, internal_name text not null, headline text not null, subheadline text, description text not null, image text, offer_type text not null, product_id text references public.products(id), bundle_id text references public.bundles(id), discount_type text, discount_value integer, bonus_id text references public.bonuses(id), cta_text text not null, secondary_text text, active boolean not null default true, start_date timestamptz, end_date timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.orders (id text primary key, order_number text not null unique, customer_name text, customer_email text, status text not null default 'pending', payment_status text not null default 'pending', subtotal integer not null, discount integer not null default 0, total integer not null, currency text not null default 'BRL', stripe_payment_intent_id text unique, stripe_checkout_session_id text unique, stripe_customer_id text, download_token text unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.order_items (id text primary key, order_id text not null references public.orders(id) on delete cascade, product_id text references public.products(id), bundle_id text references public.bundles(id), title_snapshot text not null, quantity integer not null default 1, unit_price integer not null, total integer not null, item_type text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.digital_assets (id text primary key, product_id text not null references public.products(id), file_key text not null, file_name text not null, content_type text not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.testimonials (id text primary key, name text not null, text text not null, photo text, rating integer not null check (rating between 1 and 5), city text, verified boolean not null default false, active boolean not null default false, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.faqs (id text primary key, question text not null, answer text not null, active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.sales_page_configs (id text primary key, internal_name text not null, content jsonb not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.urgency_campaigns (id text primary key, name text not null, message text not null, start_date timestamptz, end_date timestamptz, active boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.promotions (id text primary key, name text not null, code text unique, discount_type text not null, discount_value integer not null, conditions jsonb, active boolean not null default true, start_date timestamptz, end_date timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.seo_configs (id text primary key, route text not null unique, title text not null, description text not null, canonical text, open_graph_image text, structured_data jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.keywords (id text primary key, keyword text not null unique, category text not null, priority integer not null default 0, intent text not null, pages jsonb, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.analytics_events (id text primary key, name text not null, session_id text, order_id text references public.orders(id), payload jsonb, created_at timestamptz not null default now());
create table if not exists public.site_settings (key text primary key, value jsonb not null, updated_at timestamptz not null default now());
create table if not exists public.pixel_integrations (id text primary key, provider text not null unique, public_id text, active boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.processed_webhooks (id text primary key, type text not null, processed_at timestamptz not null default now());

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_customer_email_idx on public.orders(customer_email);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);

do $$
declare table_name text;
begin
  foreach table_name in array array['admin_users','product_categories','products','product_images','bundles','bundle_items','order_bumps','cart_offers','bonuses','exit_offers','orders','order_items','digital_assets','testimonials','faqs','sales_page_configs','urgency_campaigns','promotions','seo_configs','keywords','analytics_events','site_settings','pixel_integrations','processed_webhooks']
  loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end $$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('vovo-tereza-files', 'vovo-tereza-files', false, 52428800, array['image/jpeg','image/png','image/webp','image/avif','application/pdf'])
on conflict (id) do update set public = excluded.public, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
